project:
  type: website

website:
  title: "Triangle Bengali Association"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Events"
        href: events.qmd
      - text: "Contact"
        href: contact.qmd
format:
  html:
    theme: cosmo
    css: styles.css
